route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'telegram_bot'

receivers:
  - name: 'telegram_bot'
    telegram_configs:
      - bot_token: '8647077830:AAGwMuVlN7t6GGmohKrab5bUIGD5vFaSWt0'
        chat_id: 214325677
        parse_mode: 'HTML'