version: '3.8'

services:
  php:
    build:
      context: ./AppVendor/php-docker
    container_name: php-fpm
    volumes:
      - ./AppVendor/auto-part-shop:/var/www/html  # Монтируем директорию с приложением
    networks:
      - mynetwork
    depends_on:
      - db
    ports:
      - "9000:9000"
    environment:
      - PHP_DISPLAY_ERRORS=on
      - PHP_MEMORY_LIMIT=512M

  nginx:
    build:
      context: ./AppVendor/nginx-docker
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./AppVendor/nginx-docker/default.conf:/etc/nginx/conf.d/default.conf  # Конфигурация nginx
    networks:
      - mynetwork
    depends_on:
      - php

  db:
    build:
      context: ./AppVendor/postgres-docker
    container_name: my-postgres-container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: auto-part-shop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Монтируем volume для хранения данных
      - ./AppVendor/postgres-docker/postgresql.conf:/etc/postgresql/postgresql.conf.sample  # Конфигурация PostgreSQL
      - ./AppVendor/postgres-docker/pg_hba.conf:/etc/postgresql/pg_hba.conf  # Конфигурация безопасности PostgreSQL
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  pgdata:  # Определяем volume для хранения данных PostgreSQL