server {
    listen 80;
    server_name localhost;

    root /var/www/html/auto-parts-shop;  # Указываем путь на контейнер PHP-FPM

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php-fpm:9000;  # Контейнер PHP (имя контейнера)
        fastcgi_param SCRIPT_FILENAME /var/www/html/auto-parts-shop$fastcgi_script_name;  # Путь к PHP файлу внутри PHP-FPM
        include fastcgi_params;
    }
}